baseURL = 'https://nakil.org/'
languageCode = 'tr'
title = ' '
theme = 'PaperMod'
icon = 'https://www.nakil.org/favicon.ico'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  favicon = 'favicon.ico'
  ShowShareButtons = false
  defaultTheme = 'dark'
	label.icon = "/nakil.png"


  [assets]
    _favicon = 'https://www.nakil.org/favicon.ico'

[menus]
  [[menus.main]]
    identifier = 'Etiketler'
    name = 'Etiketler'
    pageRef = '/tags/'
    weight = 1
  [[menus.main]]
    identifier = 'Ara'
    name = 'Ara'
    pageRef = '/search/'
    weight = 2

[outputs]
  home = ['html', 'rss', 'json']
