baseURL = 'https://nakil.org/'
languageCode = 'tr'
title = 'NAkil Yorumlar'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  ShowShareButtons = false
  defaultTheme = 'dark'


[menus]
  [[menus.main]]
    identifier = 'Etiketler'
    name = 'Etiketler'
    pageRef = '/tags/'
  [[menus.main]]
    identifier = 'Search'
    name = 'Search'
    pageRef = '/search/'

[outputs]
  home = ['html', 'rss', 'json']
  section = ['html', 'rss', 'json']
  taxonomy = ['html', 'rss', 'json']